"""add_remove_to_accounts

Revision ID: 1abf9e52c4e7
Revises: 355b644453f9
Create Date: 2017-10-10 04:43:20.739625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1abf9e52c4e7'
down_revision = '355b644453f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('remove', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'remove')
    # ### end Alembic commands ###
