"""drop sighting_users

Revision ID: 24fad7bbfc10
Revises: 6146e792cabf
Create Date: 2017-10-22 11:45:40.968564

"""
from alembic import op
import sqlalchemy as sa
import sys
from pathlib import Path
monocle_dir = str(Path(__file__).resolve().parents[2])
if monocle_dir not in sys.path:
    sys.path.append(monocle_dir)
from monocle import db as db

# revision identifiers, used by Alembic.
revision = '24fad7bbfc10'
down_revision = '6146e792cabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sighting_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sighting_users',
    sa.Column('id', db.PRIMARY_HUGE_TYPE, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('sighting_id', db.HUGE_TYPE, nullable=False),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'sighting_id', name='ix_username_sighting_id')
    )
    op.create_index(op.f('ix_sighting_users_sighting_id'), 'sighting_users', ['sighting_id'], unique=False)
    # ### end Alembic commands ###
