"""add index to reason

Revision ID: 25f7b98fdc8c
Revises: 7b92b22434c3
Create Date: 2017-10-11 08:40:45.755076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25f7b98fdc8c'
down_revision = '7b92b22434c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_reason'), 'accounts', ['reason'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_reason'), table_name='accounts')
    # ### end Alembic commands ###
