"""add_accounts

Revision ID: 355b644453f9
Revises: e10a938e5801
Create Date: 2017-10-05 10:25:41.180601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '355b644453f9'
down_revision = 'e10a938e5801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=12), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('device_version', sa.String(length=20), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('hibernated', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=12), nullable=True),
    sa.Column('captchaed', sa.Integer(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='ix_accounts_username_unique')
    )
    op.create_index(op.f('ix_accounts_hibernated'), 'accounts', ['hibernated'], unique=False)
    op.create_index(op.f('ix_accounts_captchaed'), 'accounts', ['captchaed'], unique=False)
    op.create_index(op.f('ix_accounts_instance'), 'accounts', ['instance'], unique=False)
    op.create_index(op.f('ix_accounts_level'), 'accounts', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_level'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_instance'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_captchaed'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_hibernated'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
