"""add last_modified to gym_defenders

Revision ID: 35dee4fce912
Revises: 5f84a4df8243
Create Date: 2017-11-01 14:27:52.303046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35dee4fce912'
down_revision = '5f84a4df8243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gym_defenders', sa.Column('last_modified', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gym_defenders', 'last_modified')
    # ### end Alembic commands ###
