"""add team to gym_defenders

Revision ID: 3af369660743
Revises: 35dee4fce912
Create Date: 2017-11-01 15:19:44.061833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sys
from pathlib import Path
monocle_dir = str(Path(__file__).resolve().parents[2])
if monocle_dir not in sys.path:
    sys.path.append(monocle_dir)
from monocle import db as db

# revision identifiers, used by Alembic.
revision = '3af369660743'
down_revision = '35dee4fce912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gym_defenders', sa.Column('team', db.TINY_TYPE, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gym_defenders', 'team')
    # ### end Alembic commands ###
