"""Added last_updated columns strategically

Revision ID: 4e4814bebf31
Revises: 32aede9e7e69
Create Date: 2017-09-29 14:10:22.478961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4814bebf31'
down_revision = '32aede9e7e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fort_sightings', sa.Column('last_updated', sa.TIMESTAMP(), nullable=True))
    op.add_column('pokestops', sa.Column('last_updated', sa.TIMESTAMP(), nullable=True))
    op.add_column('sightings', sa.Column('last_updated', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sightings', 'last_updated')
    op.drop_column('pokestops', 'last_updated')
    op.drop_column('fort_sightings', 'last_updated')
    # ### end Alembic commands ###
