"""add last_hibernated to accounts

Revision ID: 5f84a4df8243
Revises: 5d2d29a14613
Create Date: 2017-11-01 14:27:03.676758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f84a4df8243'
down_revision = '5d2d29a14613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_hibernated', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_accounts_last_hibernated'), 'accounts', ['last_hibernated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_last_hibernated'), table_name='accounts')
    op.drop_column('accounts', 'last_hibernated')
    # ### end Alembic commands ###
