"""change pokemon id

Revision ID: 6146e792cabf
Revises: 436fca55d46a
Create Date: 2017-10-20 23:47:06.314713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects.mysql.mysqldb import MySQLDialect_mysqldb

# revision identifiers, used by Alembic.
revision = '6146e792cabf'
down_revision = '436fca55d46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if isinstance(op.get_context().bind.engine.dialect, MySQLDialect_mysqldb):
        op.alter_column('fort_sightings', 'guard_pokemon_id',
                   existing_type=mysql.TINYINT(display_width=3, unsigned=True),
                   type_=sa.SmallInteger(),
                   existing_nullable=True)
        op.alter_column('gym_defenders', 'pokemon_id',
                   existing_type=mysql.INTEGER(display_width=11),
                   type_=sa.SmallInteger(),
                   existing_nullable=True)
        op.alter_column('mystery_sightings', 'pokemon_id',
                   existing_type=mysql.TINYINT(display_width=3, unsigned=True),
                   type_=sa.SmallInteger(),
                   existing_nullable=True)
        op.alter_column('raids', 'pokemon_id',
                   existing_type=mysql.TINYINT(display_width=3, unsigned=True),
                   type_=sa.SmallInteger(),
                   existing_nullable=True)
        op.alter_column('sightings', 'pokemon_id',
                   existing_type=mysql.TINYINT(display_width=3, unsigned=True),
                   type_=sa.SmallInteger(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if isinstance(op.get_context().bind.engine.dialect, MySQLDialect_mysqldb):
        op.alter_column('sightings', 'pokemon_id',
                   existing_type=sa.SmallInteger(),
                   type_=mysql.TINYINT(display_width=3, unsigned=True),
                   existing_nullable=True)
        op.alter_column('raids', 'pokemon_id',
                   existing_type=sa.SmallInteger(),
                   type_=mysql.TINYINT(display_width=3, unsigned=True),
                   existing_nullable=True)
        op.alter_column('mystery_sightings', 'pokemon_id',
                   existing_type=sa.SmallInteger(),
                   type_=mysql.TINYINT(display_width=3, unsigned=True),
                   existing_nullable=True)
        op.alter_column('gym_defenders', 'pokemon_id',
                   existing_type=sa.SmallInteger(),
                   type_=mysql.INTEGER(display_width=11),
                   existing_nullable=True)
        op.alter_column('fort_sightings', 'guard_pokemon_id',
                   existing_type=sa.SmallInteger(),
                   type_=mysql.TINYINT(display_width=3, unsigned=True),
                   existing_nullable=True)
    # ### end Alembic commands ###
