"""remove_last_updated

Revision ID: 7b92b22434c3
Revises: 1abf9e52c4e7
Create Date: 2017-10-10 04:44:43.380099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b92b22434c3'
down_revision = '1abf9e52c4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fort_sightings', 'last_updated')
    op.drop_column('pokestops', 'last_updated')
    op.drop_column('sightings', 'last_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sightings', sa.Column('last_updated', mysql.TIMESTAMP(), nullable=True))
    op.add_column('pokestops', sa.Column('last_updated', mysql.TIMESTAMP(), nullable=True))
    op.add_column('fort_sightings', sa.Column('last_updated', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
