"""Added existing tables

Revision ID: f19fc04ba856
Revises: 
Create Date: 2017-09-24 03:10:27.208231

"""
from alembic import op
import sqlalchemy as sa
import sys
from pathlib import Path
monocle_dir = str(Path(__file__).resolve().parents[2])
if monocle_dir not in sys.path:
    sys.path.append(monocle_dir)
from monocle import db as db

# revision identifiers, used by Alembic.
revision = 'f19fc04ba856'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    #if db._engine.dialect.has_table(db._engine, 'sightings'):
    #    return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=35), nullable=True),
    sa.Column('lat', db.FLOAT_TYPE, nullable=True),
    sa.Column('lon', db.FLOAT_TYPE, nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_coords', 'forts', ['lat', 'lon'], unique=False)
    op.create_table('mystery_sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', db.TINY_TYPE, nullable=True),
    sa.Column('spawn_id', sa.BigInteger(), nullable=True),
    sa.Column('encounter_id', db.UNSIGNED_HUGE_TYPE, nullable=True),
    sa.Column('lat', db.FLOAT_TYPE, nullable=True),
    sa.Column('lon', db.FLOAT_TYPE, nullable=True),
    sa.Column('first_seen', sa.Integer(), nullable=True),
    sa.Column('first_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('last_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('seen_range', sa.SmallInteger(), nullable=True),
    sa.Column('atk_iv', db.TINY_TYPE, nullable=True),
    sa.Column('def_iv', db.TINY_TYPE, nullable=True),
    sa.Column('sta_iv', db.TINY_TYPE, nullable=True),
    sa.Column('move_1', sa.SmallInteger(), nullable=True),
    sa.Column('move_2', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('form', sa.SmallInteger(), nullable=True),
    sa.Column('cp', sa.SmallInteger(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id', 'spawn_id', name='unique_encounter')
    )
    op.create_index(op.f('ix_mystery_sightings_encounter_id'), 'mystery_sightings', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_mystery_sightings_first_seen'), 'mystery_sightings', ['first_seen'], unique=False)
    op.create_index(op.f('ix_mystery_sightings_spawn_id'), 'mystery_sightings', ['spawn_id'], unique=False)
    op.create_table('pokestops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=35), nullable=True),
    sa.Column('lat', db.FLOAT_TYPE, nullable=True),
    sa.Column('lon', db.FLOAT_TYPE, nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_pokestops_lat'), 'pokestops', ['lat'], unique=False)
    op.create_index(op.f('ix_pokestops_lon'), 'pokestops', ['lon'], unique=False)
    op.create_table('sightings',
    sa.Column('id', db.PRIMARY_HUGE_TYPE, nullable=False),
    sa.Column('pokemon_id', db.TINY_TYPE, nullable=True),
    sa.Column('spawn_id', sa.BigInteger(), nullable=True),
    sa.Column('expire_timestamp', sa.Integer(), nullable=True),
    sa.Column('encounter_id', db.UNSIGNED_HUGE_TYPE, nullable=True),
    sa.Column('lat', db.FLOAT_TYPE, nullable=True),
    sa.Column('lon', db.FLOAT_TYPE, nullable=True),
    sa.Column('atk_iv', db.TINY_TYPE, nullable=True),
    sa.Column('def_iv', db.TINY_TYPE, nullable=True),
    sa.Column('sta_iv', db.TINY_TYPE, nullable=True),
    sa.Column('move_1', sa.SmallInteger(), nullable=True),
    sa.Column('move_2', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('form', sa.SmallInteger(), nullable=True),
    sa.Column('cp', sa.SmallInteger(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id', 'expire_timestamp', name='timestamp_encounter_id_unique')
    )
    op.create_index(op.f('ix_sightings_encounter_id'), 'sightings', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_sightings_expire_timestamp'), 'sightings', ['expire_timestamp'], unique=False)
    op.create_table('spawnpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spawn_id', sa.BigInteger(), nullable=True),
    sa.Column('despawn_time', sa.SmallInteger(), nullable=True),
    sa.Column('lat', db.FLOAT_TYPE, nullable=True),
    sa.Column('lon', db.FLOAT_TYPE, nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('duration', db.TINY_TYPE, nullable=True),
    sa.Column('failures', db.TINY_TYPE, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spawnpoints_despawn_time'), 'spawnpoints', ['despawn_time'], unique=False)
    op.create_index(op.f('ix_spawnpoints_spawn_id'), 'spawnpoints', ['spawn_id'], unique=True)
    op.create_index(op.f('ix_spawnpoints_updated'), 'spawnpoints', ['updated'], unique=False)
    op.create_table('fort_sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fort_id', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.Integer(), nullable=True),
    sa.Column('team', db.TINY_TYPE, nullable=True),
    sa.Column('guard_pokemon_id', db.TINY_TYPE, nullable=True),
    sa.Column('slots_available', sa.SmallInteger(), nullable=True),
    sa.Column('is_in_battle', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fort_id'], ['forts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fort_id', 'last_modified', name='fort_id_last_modified_unique')
    )
    op.create_index(op.f('ix_fort_sightings_last_modified'), 'fort_sightings', ['last_modified'], unique=False)
    op.create_table('gym_defenders',
    sa.Column('id', db.PRIMARY_HUGE_TYPE, nullable=False),
    sa.Column('fort_id', sa.Integer(), nullable=False),
    sa.Column('external_id', db.UNSIGNED_HUGE_TYPE, nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('stamina_max', sa.Integer(), nullable=True),
    sa.Column('atk_iv', sa.SmallInteger(), nullable=True),
    sa.Column('def_iv', sa.SmallInteger(), nullable=True),
    sa.Column('sta_iv', sa.SmallInteger(), nullable=True),
    sa.Column('move_1', sa.SmallInteger(), nullable=True),
    sa.Column('move_2', sa.SmallInteger(), nullable=True),
    sa.Column('battles_attacked', sa.Integer(), nullable=True),
    sa.Column('battles_defended', sa.Integer(), nullable=True),
    sa.Column('num_upgrades', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fort_id'], ['forts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_defenders_created'), 'gym_defenders', ['created'], unique=False)
    op.create_index(op.f('ix_gym_defenders_fort_id'), 'gym_defenders', ['fort_id'], unique=False)
    op.create_table('raids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.BigInteger(), nullable=True),
    sa.Column('fort_id', sa.Integer(), nullable=True),
    sa.Column('level', db.TINY_TYPE, nullable=True),
    sa.Column('pokemon_id', db.TINY_TYPE, nullable=True),
    sa.Column('move_1', sa.SmallInteger(), nullable=True),
    sa.Column('move_2', sa.SmallInteger(), nullable=True),
    sa.Column('time_spawn', sa.Integer(), nullable=True),
    sa.Column('time_battle', sa.Integer(), nullable=True),
    sa.Column('time_end', sa.Integer(), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fort_id'], ['forts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_raids_time_spawn'), 'raids', ['time_spawn'], unique=False)
    op.create_table('sighting_users',
    sa.Column('id', db.PRIMARY_HUGE_TYPE, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('sighting_id', db.HUGE_TYPE, nullable=False),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'sighting_id', name='ix_username_sighting_id')
    )
    op.create_index(op.f('ix_sighting_users_sighting_id'), 'sighting_users', ['sighting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_sighting_users_sighting_id'), table_name='sighting_users')
    op.drop_table('sighting_users')
    #op.drop_index(op.f('ix_raids_time_spawn'), table_name='raids')
    op.drop_table('raids')
    #op.drop_index(op.f('ix_gym_defenders_fort_id'), table_name='gym_defenders')
    #op.drop_index(op.f('ix_gym_defenders_created'), table_name='gym_defenders')
    op.drop_table('gym_defenders')
    #op.drop_index(op.f('ix_fort_sightings_last_modified'), table_name='fort_sightings')
    op.drop_table('fort_sightings')
    #op.drop_index(op.f('ix_spawnpoints_updated'), table_name='spawnpoints')
    #op.drop_index(op.f('ix_spawnpoints_spawn_id'), table_name='spawnpoints')
    #op.drop_index(op.f('ix_spawnpoints_despawn_time'), table_name='spawnpoints')
    op.drop_table('spawnpoints')
    #op.drop_index(op.f('ix_sightings_expire_timestamp'), table_name='sightings')
    #op.drop_index(op.f('ix_sightings_encounter_id'), table_name='sightings')
    op.drop_table('sightings')
    #op.drop_index(op.f('ix_pokestops_lon'), table_name='pokestops')
    #op.drop_index(op.f('ix_pokestops_lat'), table_name='pokestops')
    op.drop_table('pokestops')
    #op.drop_index(op.f('ix_mystery_sightings_spawn_id'), table_name='mystery_sightings')
    #op.drop_index(op.f('ix_mystery_sightings_first_seen'), table_name='mystery_sightings')
    #op.drop_index(op.f('ix_mystery_sightings_encounter_id'), table_name='mystery_sightings')
    op.drop_table('mystery_sightings')
    #op.drop_index('ix_coords', table_name='forts')
    op.drop_table('forts')
    # ### end Alembic commands ###
